name: Release

on:
  push:
    tags:
      - 'v*'
  push:
    branches: [main, dev]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, 386]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o gh-copilot-insights-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: gh-copilot-insights-${{ matrix.os }}-${{ matrix.arch }}
          path: gh-copilot-insights-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}

  release:
    if: startsWith(github.ref, 'refs/tags/v') && github.event.repository.protected
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: gh-copilot-insights-${{ matrix.os }}-${{ matrix.arch }}
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gh-copilot-insights-windows-amd64.exe
            gh-copilot-insights-linux-amd64
            gh-copilot-insights-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}